name: C/C++ CI

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        std: [c++17, c++20, c++23]
        cxx: [g++-9, g++-10, g++-11, g++-12, g++-13, g++-14]
    steps:    
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt-get update && apt-cache search clang- && sudo apt-get install -y libgtest-dev ${{ matrix.cxx }}
    - name: build tests
      run: make -C test -j$(nproc) CXX=${{ matrix.cxx }} STD=${{ matrix.std }}  
    - name: run tests
      run: make -C test -j$(nproc) CXX=${{ matrix.cxx }} STD=${{ matrix.std }} run-tests 
