name: C/C++ CI

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        std: [c++17, c++20, c++23]
        cxx: [g++-9, g++-10, g++-11, g++-12, g++-13, g++-14, clang++-14, clang++-15, clang++-16, clang++-17, clang++-18]
    steps:    
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt-get update && sudo apt-get install -y libgtest-dev ${{ matrix.cxx }}
    - name: run tests
      run: make -C test -j$(nproc) CXX=${{ matrix.cxx }} STD=${{ matrix.cxx }} run-tests 
