name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v4
    - name: install gtest
      run: sudo apt-get update && sudo apt-get install libgtest-dev
    - name: run tests
      run: make run-tests -j$(nproc)
