name: C/C++ CI

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        std: [c++17, c++20, c++23]
        cxx: [clang++-15, clang++-16, clang++-17]
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt-get update && sudo apt-get install -y libgtest-dev clang-15 clang-16 clang-17
    - name: build tests
      run: make -C test -j$(nproc) CXX=${{ matrix.cxx }} STD=${{ matrix.std }}  
    - name: run tests
      run: make -C test -j$(nproc) CXX=${{ matrix.cxx }} STD=${{ matrix.std }} run-tests 
